Repository privacy-scaling-explorations/maci-platform, pull requests merged in 2024-12, with the labels that each got.

#534 fix(landing-page): fixed bug with multi round
  packages/interface/src/pages/index.tsx
Labels: bug

#535 fix: nav bar display and the singleRound stuff
  packages/interface/src/features/ballot/components/BallotConfirmation.tsx
  packages/interface/src/layouts/types.ts
  packages/interface/src/pages/index.tsx
  packages/interface/src/pages/rounds/[pollId]/applications/confirmation.tsx
  packages/interface/src/pages/rounds/[pollId]/applications/index.tsx
  packages/interface/src/pages/rounds/[pollId]/applications/new.tsx
  packages/interface/src/pages/rounds/[pollId]/ballot/confirmation.tsx
Labels: bug

#544 fix: ballot page refresh redirect to homepage
  packages/interface/src/layouts/BaseLayout.tsx
  packages/interface/src/layouts/types.ts
  packages/interface/src/pages/rounds/[pollId]/ballot/index.tsx
Labels: bug

#532 chore: improve the ballot submission process
  packages/interface/src/components/BallotOverview.tsx
  packages/interface/src/components/Info.tsx
  packages/interface/src/contexts/Maci.tsx
  packages/interface/src/contexts/types.ts
  packages/interface/src/features/ballot/components/SubmitBallotButton.tsx
  packages/interface/src/layouts/DefaultLayout.tsx
Labels: chore

#546 feat(coordinator): update maci packages
  .github/workflows/coordinator-build.yml
  package.json
  packages/coordinator/.env.example
  packages/coordinator/package.json
  packages/coordinator/scripts/downloadZKeys.ts
  packages/coordinator/tests/app.test.ts
  packages/coordinator/tests/e2e.aa.test.ts
  packages/coordinator/ts/common/__tests__/common.test.ts
  packages/coordinator/ts/common/accountAbstraction.ts
  packages/coordinator/ts/common/errors.ts
  packages/coordinator/ts/crypto/__tests__/crypto.service.test.ts
  packages/coordinator/ts/crypto/crypto.service.ts
  packages/coordinator/ts/file/__tests__/file.service.test.ts
  packages/coordinator/ts/file/file.service.ts
  packages/coordinator/ts/proof/__tests__/proof.service.test.ts
  packages/coordinator/ts/proof/proof.service.ts
  packages/coordinator/ts/proof/types.ts
  packages/coordinator/ts/sessionKeys/__tests__/sessionKeys.service.test.ts
  packages/coordinator/ts/sessionKeys/sessionKeys.service.ts
  packages/coordinator/ts/subgraph/__tests__/subgraph.service.test.ts
  packages/coordinator/ts/subgraph/subgraph.service.ts
  pnpm-lock.yaml
Labels: enhancement

#549 fix: adjust ui styling
  packages/interface/src/features/ballot/components/ProjectAvatarWithName.tsx
  packages/interface/src/features/rounds/components/RoundItem.tsx
  packages/interface/src/features/rounds/components/RoundsList.tsx
  packages/interface/src/pages/index.tsx
Labels: bug
