Repository privacy-scaling-explorations/maci-platform, pull requests merged in 2024-11, with the labels that each got.

#432 feat(contracts): add max cap for allocated amount
  packages/contracts/contracts/interfaces/IPayoutStrategy.sol
  packages/contracts/contracts/maci/Tally.sol
  packages/contracts/deploy-config-example.json
  packages/contracts/tasks/deploy/poll/01-poll.ts
  packages/contracts/tests/Tally.test.ts
Labels: enhancement

#434 feat(contracts): set contract names for deployment helper service
  packages/contracts/deploy-config-example.json
  packages/contracts/hardhat.config.ts
  packages/contracts/package.json
  packages/contracts/tasks/deploy/maci/05-pollFactory.ts
  packages/contracts/tasks/deploy/maci/07-tallyFactory.ts
  packages/contracts/tasks/deploy/maci/08-maci.ts
  packages/contracts/tasks/deploy/maci/10-registryManager.ts
  packages/contracts/tasks/deploy/poll/01-poll.ts
  packages/contracts/tasks/helpers/constants/index.ts
  packages/contracts/tasks/runner/initPoll.ts
  packages/contracts/tasks/runner/merge.ts
  packages/contracts/tasks/runner/prove.ts
  packages/contracts/tasks/runner/submitOnChain.ts
  packages/contracts/tests/utils.ts
  pnpm-lock.yaml
Labels: enhancement

#438 fix(subgraph): add create tally handler to parse tally events
  packages/contracts/tasks/deploy/poll/01-poll.ts
  packages/coordinator/scripts/downloadZKeys.ts
  packages/subgraph/config/network.json
  packages/subgraph/src/maci.ts
  packages/subgraph/src/utils/entity.ts
  packages/subgraph/tests/common.ts
  packages/subgraph/tests/poll/poll.test.ts
Labels: bug

#439 fix(subgraph): create template for tally to start parsing events
  packages/subgraph/src/maci.ts
  packages/subgraph/templates/subgraph.template.yaml
Labels: bug

#444 chore: move e2e tests to a separate package
  .eslintignore
  .github/workflows/e2e.yml
  package.json
  packages/e2e/.env.example
  packages/e2e/.eslintrc.cjs
  packages/e2e/.gitignore
  packages/e2e/package.json
  packages/e2e/playwright.config.ts
  packages/e2e/test/connectWallet.test.ts
  packages/e2e/test/constants.ts
  packages/e2e/test/wallet-setup/basic.setup.ts
  packages/e2e/test/wallet-setup/connected.setup.ts
  packages/e2e/tsconfig.json
  packages/interface/.eslintrc.js
  packages/interface/.npmrc
  packages/interface/e2e/connectWallet.test.ts
  packages/interface/package.json
  packages/interface/playwright/constants.ts
  packages/interface/playwright/fixtures.ts
  packages/interface/playwright/types.d.ts
  packages/interface/tsconfig.build.json
  packages/interface/tsconfig.json
  pnpm-lock.yaml
Labels: chore

#464 chore: remove caching for synpress runs
  .github/workflows/e2e.yml
Labels: chore

#470 fix: update the maci-contracts package version
  packages/contracts/package.json
  packages/coordinator/package.json
  packages/interface/package.json
  pnpm-lock.yaml
Labels: bug
