Repository privacy-scaling-explorations/maci-platform, pull requests merged in 2024-09, with the labels that each got.

#320 docs: add maci/ux limitations
  docs/02_adding_projects.md
  docs/04_voting.md
Labels: documentation

#298 feat(subgraph): add subgraph support
  .eslintignore
  .prettierignore
  packages/contracts/contracts/interfaces/IRecipientRegistry.sol
  packages/contracts/contracts/interfaces/IRegistryManager.sol
  packages/contracts/contracts/maci/MACI.sol
  packages/contracts/contracts/maci/PollFactory.sol
  packages/contracts/contracts/registryManager/RegistryManager.sol
  packages/contracts/package.json
  packages/contracts/tasks/deploy/poll/01-poll.ts
  packages/contracts/tasks/runner/initPoll.ts
  packages/contracts/tests/EASRegistryManager.test.ts
  packages/contracts/tests/Maci.test.ts
  packages/contracts/tests/RegistryManager.test.ts
  packages/subgraph/.eslintrc.js
  packages/subgraph/.gitignore
  packages/subgraph/README.md
  packages/subgraph/config/network.json
  packages/subgraph/docker-compose.yaml
  packages/subgraph/matchstick.yaml
  packages/subgraph/package.json
  packages/subgraph/schemas/schema.v1.graphql
  packages/subgraph/src/@types/global.d.ts
  packages/subgraph/src/maci.ts
  packages/subgraph/src/poll.ts
  packages/subgraph/src/registry.ts
  packages/subgraph/src/registryManager.ts
  packages/subgraph/src/utils/constants.ts
  packages/subgraph/src/utils/entity.ts
  packages/subgraph/templates/subgraph.template.yaml
  packages/subgraph/tests/common.ts
  packages/subgraph/tests/maci/maci.test.ts
  packages/subgraph/tests/maci/utils.ts
  packages/subgraph/tests/poll/poll.test.ts
  packages/subgraph/tests/poll/utils.ts
  packages/subgraph/tests/registry/registry.test.ts
  packages/subgraph/tests/registry/utils.ts
  packages/subgraph/tests/registryManager/registryManager.test.ts
  packages/subgraph/tests/registryManager/utils.ts
  packages/subgraph/tsconfig.build.json
  packages/subgraph/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement

#328 docs(contracts): add draft docs for contracts
  packages/contracts/.gitignore
  packages/contracts/docs/diagram.svg
  packages/contracts/docs/platform.md
  packages/contracts/package.json
  packages/contracts/scripts/generateUml.ts
  pnpm-lock.yaml
Labels: documentation

#329 docs(contracts): keep high level description for contracts
  packages/contracts/docs/platform.md
Labels: documentation

#334 chore: update the wordings
  packages/interface/src/components/BallotOverview.tsx
  packages/interface/src/components/VotingUsage.tsx
  packages/interface/src/contexts/Maci.tsx
  packages/interface/src/features/applications/components/ReviewBar.tsx
  packages/interface/src/features/ballot/components/BallotConfirmation.tsx
  packages/interface/src/features/projects/components/Projects.tsx
  packages/interface/src/pages/applications/confirmation.tsx
  packages/interface/src/pages/applications/new.tsx
  packages/interface/src/pages/ballot/index.tsx
Labels: chore

#336 chore: update info and ballot overview display
  packages/interface/src/components/BallotOverview.tsx
  packages/interface/src/components/Info.tsx
  packages/interface/src/components/VotingInfo.tsx
  packages/interface/src/layouts/DefaultLayout.tsx
  packages/interface/src/pages/signup/index.tsx
Labels: chore

#348 fix(subgraph): remove call handler and use events for poll init
  packages/contracts/contracts/maci/Poll.sol
  packages/subgraph/config/network.json
  packages/subgraph/src/poll.ts
  packages/subgraph/templates/subgraph.template.yaml
  packages/subgraph/tests/poll/poll.test.ts
  packages/subgraph/tests/poll/utils.ts
Labels: bug

#350 chore: add simple registry and move some arguments to registry config
  packages/contracts/contracts/registry/SimpleRegistry.sol
  packages/contracts/deploy-config-example.json
  packages/contracts/tasks/deploy/poll/01-poll.ts
  packages/contracts/tasks/helpers/constants/index.ts
Labels: chore
