Repository privacy-scaling-explorations/maci-platform, pull requests merged in 2025-01, with the labels that each got.

#591 chore: remove unused packages
  packages/coordinator/package.json
  pnpm-lock.yaml
Labels: chore

#590 fix: tally result id collision
  packages/interface/src/server/api/routers/results.ts
  packages/subgraph/README.md
  packages/subgraph/package.json
  packages/subgraph/src/utils/entity.ts
  packages/subgraph/tests/tally/tally.test.ts
Labels: bug

#541 feat: display the projects created by the user
  packages/interface/src/features/applications/components/ApplicationForm.tsx
  packages/interface/src/features/applications/components/ReviewApplicationDetails.tsx
  packages/interface/src/features/applications/hooks/useApplicationById.ts
  packages/interface/src/features/applications/hooks/useApplications.ts
  packages/interface/src/features/applications/hooks/useCreateApplication.ts
  packages/interface/src/features/applications/types/index.ts
  packages/interface/src/features/projects/components/ProjectItem.tsx
  packages/interface/src/features/projects/components/ProjectsResults.tsx
  packages/interface/src/features/rounds/components/Projects.tsx
  packages/interface/src/hooks/useRegistry.ts
  packages/interface/src/pages/rounds/[pollId]/applications/confirmation.tsx
  packages/interface/src/server/api/routers/applications.ts
  packages/interface/src/server/api/routers/projects.ts
  packages/interface/src/utils/fetchApplications.ts
  packages/interface/src/utils/fetchProjects.ts
Labels: enhancement

#603 feat(filter): project search bar + ui bugs
  packages/interface/.env.example
  packages/interface/src/components/ImageUpload.tsx
  packages/interface/src/components/SingleRoundHome.tsx
  packages/interface/src/components/SortFilter.tsx
  packages/interface/src/features/rounds/components/Projects.tsx
  packages/interface/src/layouts/BaseLayout.tsx
  packages/interface/src/providers/index.tsx
  packages/interface/src/server/api/routers/projects.ts
  packages/interface/src/utils/fetchProjects.ts
  packages/interface/src/utils/types.ts
Labels: enhancement, frontend

#605 fix(ballot): fixes a bug where add ballot causing page error
  packages/interface/src/features/ballot/components/AllocationInput.tsx
Labels: bug

#609 chore: limit the link length and update links
  packages/interface/src/config.ts
  packages/interface/src/features/applications/components/ReviewApplicationDetails.tsx
  packages/interface/src/features/projects/components/ProjectContacts.tsx
Labels: chore, frontend

#611 fix: footer should set ssr to false since it is dynamic to screen size
  packages/interface/src/components/Footer.tsx
  packages/interface/src/layouts/BaseLayout.tsx
Labels: bug

#610 feat(glossary): added glossary, help button, renamed ballot
  packages/interface/src/components/Header.tsx
  packages/interface/src/components/HelpButton.tsx
  packages/interface/src/features/applications/components/ApplicationItem.tsx
  packages/interface/src/features/home/components/FaqList.tsx
  packages/interface/src/features/home/components/Glossary.tsx
  packages/interface/src/features/projects/components/VotingWidget.tsx
  packages/interface/src/pages/_app.tsx
  packages/interface/src/pages/index.tsx
  packages/interface/src/pages/rounds/[pollId]/ballot/index.tsx
  packages/interface/src/styles/HelpButton.css
  pnpm-lock.yaml
Labels: enhancement, frontend
